package cn.tedu.exception;

public class ExceptionDemo1 {

	public static void main(String[] args) {

		// try {
		// System.out.println(1 / 0);
		// } catch (ArithmeticException e) {
		// System.out.println("处理异常中~~~");
		// }

		int[] arr = new int[3];
		System.out.println(arr[5]);
	}

}
